### ISSUE TITLE
Resources not found

### ISSUE THREAD

**Issue by tobiasreichel** [FlorianSW/cftools-discord#10]
just finished setting up the docker 

commands work except leaderboard 

that my error what am I doing wrong?

serviceName_1  | Unknown error occurred:  ResourceNotFound [Error]: ResourceNotFound: https://data.cftools.cloud/v1/server/60f01d63be53a191d8409823/leaderboard?stat=kills&order=-1&limit=7
serviceName_1  |     at new ResourceNotFound (/app/node_modules/cftools-sdk/lib/types.js:152:28)
serviceName_1  |     at fromHttpError (/app/node_modules/cftools-sdk/lib/internal/http.js:146:16)
serviceName_1  |     at GotHttpClient.<anonymous> (/app/node_modules/cftools-sdk/lib/internal/http.js:112:31)
serviceName_1  |     at step (/app/node_modules/cftools-sdk/lib/internal/http.js:44:23)
serviceName_1  |     at Object.throw (/app/node_modules/cftools-sdk/lib/internal/http.js:25:53)
serviceName_1  |     at rejected (/app/node_modules/cftools-sdk/lib/internal/http.js:17:65)
serviceName_1  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by tobiasreichel** [comment]
I know it wants a login but where can I specify one?

**Comment by FlorianSW** [comment]
Hi 👋 

Yeah, you need to grant the app access to the server data. Go to https://developer.cftools.cloud/application/ and then open the app. There is a grant URL, copy this one and open it in a new browser tab. Then select the server and hit grant :) After that, it should work.

**Comment by tobiasreichel** [comment]
Thanks for the help

Found it out the that my mate nedded to grant me access
