### ISSUE TITLE
Disable the mention of bot 

### ISSUE THREAD

**Issue by tobiasreichel** [FlorianSW/cftools-discord#11]
just a question 

is it somehow possible to remove the need for @botname and change it to a prefix like !leaderboard ?

my users to like to write so much each time 

and yes I know its lazy

**Comment by FreezeWarfare** [comment]
should make it an option within the config. 
"Mention_bot = True or False // True = @botName !leaderboard, False = !leaderboard" 
Something like that <3

**Comment by FlorianSW** [comment]
What do you think about having it as a slash command in discord? Something like:

/leaderboard [serverName]

Where the `serverName` is also optional, depending on if multiple servers are setup or not.
??? :)

**Comment by tobiasreichel** [comment]
Would be awesome it you could implement it like that

**Comment by FreezeWarfare** [comment]
should be like /leaderboard [servername] 
bc of multi servers.

**Comment by FlorianSW** [comment]
> should be like /leaderboard [servername] bc of multi servers.

Yes, this will, however, only be the case if a command is enabled at multiple servers. I'll push a rewritten version of the bot that will exclusively use slash commands. Stay tuned :)

**Comment by FlorianSW** [comment]
See https://github.com/FlorianSW/cftools-discord/releases/tag/v2.0.0-alpha1 as an alpha version of the bot using slash commands. I would really appreciate feedback 🙏

**Comment by tobiasreichel** [comment]
Will test it right away

**Comment by tobiasreichel** [comment]
hey bud 

if I run the bot with 

`npm start

> cftools-discord@1.0.0 prestart
> npm run build

Error: EACCES: permission denied, mkdir '/root/.nvm/versions/node/v16.6.2'


> cftools-discord@1.0.0 start
> node .

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'node:events'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/docker/skvadcf/cftools-discord/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)`


but if  I run it just with    ` node . ` it will start and I don't know why?


any ideas ?

**Comment by FreezeWarfare** [comment]
> See https://github.com/FlorianSW/cftools-discord/releases/tag/v2.0.0-alpha1 as an alpha version of the bot using slash commands. I would really appreciate feedback 🙏

I'll help test it as well.

**Comment by FlorianSW** [comment]
> hey bud
> 
> if I run the bot with
> 
> `npm start
> 
> > cftools-discord@1.0.0 prestart
> > npm run build
> 
> Error: EACCES: permission denied, mkdir '/root/.nvm/versions/node/v16.6.2'
> 
> > cftools-discord@1.0.0 start
> > node .
> 
> internal/modules/cjs/loader.js:638 throw err; ^
> 
> Error: Cannot find module 'node:events' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15) at Function.Module._load (internal/modules/cjs/loader.js:562:25) at Module.require (internal/modules/cjs/loader.js:692:17) at require (internal/modules/cjs/helpers.js:25:18) at Object. (/home/docker/skvadcf/cftools-discord/node_modules/discord.js/src/client/BaseClient.js:3:22) at Module._compile (internal/modules/cjs/loader.js:778:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3)`
> 
> but if I run it just with `node .` it will start and I don't know why?
> 
> any ideas ?

What version of node do you use? I might have written the wrong requirement into the release notes. You need at least 17.6 now, thanks to what nodejs version Discordjs requires 🤷

**Comment by tobiasreichel** [comment]
updated to 17.6 now its running

quick question for what is the file commands/leaderboard.cfg

**Comment by FlorianSW** [comment]
> quick question for what is the file commands/leaderboard.cfg

Oops, that is a leftover from first iterations  🙈
I'll clean this up ☺️

**Comment by FlorianSW** [comment]
I did not hear any bad feedback so far, on the other hand I got some feedback mentioning that it works like expected :) I'm closing this issue therefore. Feel free to open a new issue when there are issues :)
