### ISSUE TITLE
Where to get the applicationId and secret in the cftools configuration object from

### ISSUE THREAD

**Issue by SneakyFresh** [FlorianSW/cftools-discord#12]
Where do I find this information ?

```
  "cftools": {
    "applicationId": "CFTools Cloud application ID",
    "secret": "CFTools Cloud application secret"
```

**Comment by FlorianSW** [comment]
You need to create an application in https://developer.cftools.cloud The information is then available on the application details. Make sure you also grant the app access to the resources (server) you want to use the bot for (using the grant URL).

**Comment by SneakyFresh** [comment]
Thank you :)
