### ISSUE TITLE
leaderboard command works, no other commands work

### ISSUE THREAD

**Issue by mr190e** [FlorianSW/cftools-discord#14]
Hello, just got the bot running, granted it access but seems like I can only pull leaderboard info. When I run "haspriority", or "playerstats" command in discord it just says "An unknown error occurred :woozy_face:".

In docker log it says:

> 
> HTTPError: Response code 401 (Unauthorized)
> 
>     at Request.<anonymous> (/app/node_modules/got/dist/source/as-promise/index.js:117:42)
> 
>     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
> 
>   code: ERR_NON_2XX_3XX_RESPONSE,

Any idea what am I doing wrong?

Is the auth for those commands any different?

**Comment by FlorianSW** [comment]
Hmm, looks good on my end 🤔 Unauthorized sounds pretty stupid as well, tbh. Do you use the latest version?

**Comment by mr190e** [comment]
Yes, just downloaded it like a week ago...

edit: saw you updated the code. Just pulled the image once more and now it works :)

**Comment by FlorianSW** [comment]
> 

Yeah, sorry for hat. Just saw that I forgot to update the cftools-sdk library to fix an issue with the lookup endpoint requiring authentication now. The update fixed that. Thanks for pointing this out! :)
