### ISSUE TITLE
Anzahl der Ränge erhöhen

### ISSUE THREAD

**Issue by Thomas200049** [FlorianSW/cftools-discord#6]
Aktuell ist ja nur eine maximale Anzahl von 7 Rängen auflistbar. Kann dies in einer Methode etwas erhöht werden?

**Comment by FlorianSW** [comment]
In der letzten Version (`main`) ist eine Änderung drin, die die Konfiguration des leaderboard Kommandos erlaubt. Die neue Konfiguration heißt `numberOfPlayers` und muss eine Zahl sein. Bspw.:

```
"commandMapping": {
  "leaderboard": {
    "command": "leaderboard",
    "config": {
      "defaultStat": "kills",
      "numberOfPlayers": 20,
      "allowedStats": [
        "kills"
      ]
    }
  }
}
```
